language: php

before_install:
    - dpkg --get-selections '*'
    - sudo apt-get update -qq;
    - sudo apt-get install -y aptitude;
    - sudo aptitude install -y gcc-multilib g++-multilib;
    - sudo mv /usr/bin/xml2-config /usr/bin/xml2-config.x86_64;
    - sudo aptitude install -y libxml2-dev:i386;
    - sudo mv /usr/bin/xml2-config /usr/bin/xml2-config.i386;
    - sudo cp /usr/bin/xml2-config.x86_64 /usr/bin/xml2-config;
    - sudo aptitude install -y zlib1g-dev:i386;

script:
    - echo 123
