language: c

before_install:
    - dpkg --get-selections '*'
    - sudo apt-get update -qq;
    - sudo apt-get install -y libgphoto2-2:i386 libsane:i386 ia32-libs-multiarch ia32-libs libc6-i386 gcc-multilib g++-multilib;
    - sudo mv /usr/bin/xml2-config /usr/bin/xml2-config.x86_64;
    - sudo apt-get install libxml2-dev:i386;
    - sudo mv /usr/bin/xml2-config /usr/bin/xml2-config.i386;
    - sudo cp /usr/bin/xml2-config.x86_64 /usr/bin/xml2-config;
    - sudo apt-get install -y ia32-libs libc6-i386 gcc-multilib g++-multilib zlib1g-dev:i386;

script:
    - echo 123
